# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        square:
            quality: 75
            filters:
                thumbnail: 
                    size: [290, 290]
                    mode: outbound
        banniere:
            quality: 80
            filters:
                upscale:
                    min: [600, 600]
                thumbnail:
                    size: [600, 400]
                    mode: outbound




